version: '3.9'
services:
  cart:
    build:
      dockerfile: ./Cart/Dockerfile
      context: ./backend
    ports:
      - '8001:80'
      - '9001:443'
    environment:
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: development
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: 'Development'
      ConnectionStrings__MongoDb: 'mongodb://root:localpassword@mongo:27017'
    volumes:
      - '~/.aspnet/https:/https:ro'
  orders:
    build:
      dockerfile: ./Orders/Dockerfile
      context: ./backend
    ports:
      - '8002:80'
      - '9002:443'
    environment:
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: development
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: 'Development'
      ConnectionStrings__MongoDb: 'mongodb://root:localpassword@mongo:27017'
    volumes:
      - '~/.aspnet/https:/https:ro'
  shipping:
    build:
      dockerfile: ./Shipping/Dockerfile
      context: ./backend
    ports:
      - '8003:80'
      - '9003:443'
    environment:
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: development
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: 'Development'
      ConnectionStrings__MongoDb: 'mongodb://root:localpassword@mongo:27017'
    volumes:
      - '~/.aspnet/https:/https:ro'

  # Message broker
  rabbitmq:
    build: rabbitmq
    volumes:
      - rabbitmq_etc:/etc/rabbitmq/
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq/
    ports:
      - 5672:5672 # amqp endpoint
      - 15672:15672 # admin portal

  # Mongo DB for persistance
  mongo:
    image: 'bitnami/mongodb:latest'
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongo
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_PASSWORD: localpassword
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: localpassword
      # MONGO_INITDB_DATABASE: my-service
      MONGO_REPLICA_SET_NAME: rs0
    ports:
      - 27017:27017
    volumes:
      - 'mongodb_volume:/bitnami'
volumes:
  mongodb_volume:
    driver: local
  rabbitmq_etc:
  rabbitmq_data:
  rabbitmq_logs:
  key_cloak_data: